#!/bin/bash

set -e

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}

  shift
  (
    set -e

    cd packages/${bosh_pkg}
    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
        if ls ../../src/${package}/*.h >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.h # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package csi-localdriver     -app github.com/jeffpak/local-node-plugin/cmd/localnodeplugin
sync_package csi-localcontroller -app github.com/jeffpak/local-controller-plugin/cmd/localcontrollerplugin
sync_package csibroker           -app code.cloudfoundry.org/csibroker

wait

git diff --name-only packages/*/spec
